function Z = plasmaDispersionFunction(z)
% PLASMADISPERSIONFUNCTION  Compute the plasma dispersion function Z(z).
%
%   Z = PLASMADISPERSIONFUNCTION(z)
%
%   This function evaluates the plasma dispersion function
%
%       Z(z) = i*sqrt(pi)*exp(-z^2)*erfc(-i*z)
%
%   using a rational multi-pole / Pade approximation:
%
%       Z(z) ~= sum_j b_j / (z - c_j).
%
%   The input z can be a scalar, vector, or matrix of complex arguments.
%   The output Z has the same size as z.
%
%
%   Physical Meaning
%   ----------------
%   The plasma dispersion function appears in kinetic plasma wave theory
%   after integrating the resonant particle response over the parallel
%   velocity distribution. In the EMIC dispersion solver, the argument is
%   usually
%
%       zeta_s = (omega - Omega_s) / (k_parallel*v_parallel_th,s),
%
%   where s denotes the ion species.
%
%
%   Numerical Method
%   ----------------
%   Instead of directly evaluating
%
%       i*sqrt(pi)*exp(-z^2)*erfc(-i*z),
%
%   this function uses a 12-pole rational approximation. The first six
%   coefficients b and c are specified explicitly, and the remaining six
%   poles are generated by conjugate symmetry:
%
%       b(7:12) = conj(b(1:6)),
%       c(7:12) = -conj(c(1:6)).
%
%   This type of approximation is commonly used in kinetic dispersion
%   solvers because it avoids numerical overflow and improves efficiency
%   compared with direct evaluation of the complex error function.
%
%
%   Inputs
%   ------
%   z : complex scalar, vector, or array
%       Argument of the plasma dispersion function.
%
%
%   Output
%   ------
%   Z : complex scalar, vector, or array
%       Approximate value of the plasma dispersion function Z(z).
%       If an element of z is NaN or Inf, the corresponding output is NaN.
%
%
%   Notes
%   -----
%   1. This function is intended for kinetic dispersion-relation solvers.
%   2. The coefficient set used here corresponds to a finite-pole
%      approximation and should be tested against a high-accuracy reference
%      function if very high precision is required.
%   3. The rational approximation is especially useful when direct
%      exp-erfc evaluation is unstable or slow.
%   4. For cold ion species with T_parallel = 0, do not call this function;
%      those species should be treated by cold-plasma terms instead.
%
%
%   Author: Xue Z.X.
%   Code development assistance: ChatGPT (GPT-5.5 Thinking), OpenAI
%   Final implementation, verification, and scientific interpretation by Xue Z.X.
%
%   See also ERFC, EXP.

Z = zeros(size(z));
b=[
    -0.004547861216840+0.000621096229879i;
    0.215155729059403-0.201505401705763i;
    0.439545043457674-4.161084685092405i;
    -20.216967308177410+12.885503528244977i;
    67.081488119986460-20.846345891864550i;
    -4.801467372237129e+01-1.072756140299431e+02i;
    ];
c=[
    2.978429162453205-2.049696666440972i;
    -2.256783783969929-2.208618411911446i;
    1.673799856114519-2.324085194217706i;
    1.159032034062764-2.406739409567887i;
    -0.682287637027822-2.460365014999888i;
    0.225365375295874-2.486779417872603i;
    ];

b(7:12)=conj(b(1:6));
c(7:12)=-conj(c(1:6));

for ii = 1:numel(z)
    zz = z(ii);

    if ~isfinite(real(zz)) || ~isfinite(imag(zz))
        Z(ii) = NaN;
        continue;
    end

    Ztmp = 0;
    for jj = 1:length(b)
        Ztmp = Ztmp + b(jj) / (zz - c(jj));
    end

    Z(ii) = Ztmp;
end

end


